drop table if exists sync_task;

create table sync_task (
	id bigint generated by default as identity,
	dst_path varchar(256),
	src_path varchar(256),
	event_type varchar(16), -- modify move delete add config
	status int default 0, -- -1:error 0:unsync ...
	file_type int default 0, -- 0:folder 1:file ...
	event_date timestamp not null,
    primary key (id)
);
