drop table if exists sync_task;

create table sync_task (
	id bigint generated by default as identity,
	dst_path varchar(256) not null,
	src_path varchar(256) not null,
	event_type varchar(16), -- modify move delete add
	event_date timestamp not null,
    primary key (id)
    dfda
);
